services:
  next-app:
    image: oven/bun:latest  # Using Bun image directly
    # image: node:18  # Using Node.js image directly
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "bun install && bun dev"
volumes:
  node_modules: {}
