services:
  next-app:
    image: node:18  # Using Node.js image directly
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run dev"
